-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE trazasexcesotiempo (
	case_id text NULL,
	"timestamp" timestamptz NULL,
	"@@index" int8 NULL,
	"@@case_index" int8 NULL,
	resuelta bool NULL
);
