-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE trazas (
	case_id text NULL,
	activity text NULL,
	"timestamp" timestamptz NULL,
	activityid text NULL,
	"@@index" int8 NULL,
	"@@case_index" int8 NULL
);
